# -----------------------------
# GEOMETRY (static; saved once)
# -----------------------------
geometry:
  file_glob: "input_sample/Run5_2023_baseline/OutTrigd_*.root"
  tree_name: "cells"
  branches:
    cell_id_in_module: "cell_id_in_module"
    module_id_in_calo: "module_id_in_calo"
    module_type: "module_type"
    x_mm: "x_mm"
    y_mm: "y_mm"
    z_mm: "z_mm"
    dx_mm: "dx_mm"
    dy_mm: "dy_mm"
    dz_mm: "dz_mm"
    ax_deg: "ax_deg"
    ay_deg: "ay_deg"
    az_deg: "az_deg"

# -----------------------------
# TRUTH (one particle per entry)
# 对齐：严格依赖 (pair_idx, entry_index)
# 不读取任何名字含 "id" 的分支
# -----------------------------
truth:
  file_glob: "input_sample/Run5_2023_baseline/fluxFiles/flux_*.root"
  tree_name: "tree"
  branches:
    entry_x: "entry_x"
    entry_y: "entry_y"
    entry_z: "entry_z"
    px: "px"
    py: "py"
    pz: "pz"
    timing: "timing"
    eTot: "eTot"

# -----------------------------
# RESPONSES (module-level)
# 自动发现 mod*_ph / mod*_t 分支
# 对齐：严格依赖 (pair_idx, entry_index)
# 不读取任何名字含 "id" 的分支
# -----------------------------
responses:
  file_glob: "input_sample/Run5_2023_baseline/OutTrigd_*.root"
  tree_name: "tree"
  regex:
    ph: "^mod(\\d+)_ph$"
    t: "^mod(\\d+)_t$"
  cfd_threshold_pe: 0.0   # pe_count 统计阈值
  time_valid_min: 0.0     # t<该值视为无效(如模拟中无信号为负)
  sparse:
    enabled: true         # 稀疏输出：只存有信号的下标与数值
    keep_dense_columns: false  # 如需同时保留 dense ph/t，设为 true

# -----------------------------
# 输出设置
# -----------------------------
output:
  parquet: true
